/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddNode: typeof import('./src/components/Widgets/AddNode.vue')['default']
    ArrayItem: typeof import('./src/components/Fields/ArrayItem.vue')['default']
    copy: typeof import('./src/components/Links/LinksWraper copy.vue')['default']
    Debug: typeof import('./src/components/Widgets/Terminal/Tabs/Debug.vue')['default']
    DefaultTemplate: typeof import('./src/components/Fields/DefaultTemplate.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DropDown: typeof import('./src/components/Fields/DropDown.vue')['default']
    FieldWraper: typeof import('./src/components/Fields/FieldWraper.vue')['default']
    Link: typeof import('./src/components/Links/Link.vue')['default']
    LinksWraper: typeof import('./src/components/Links/LinksWraper.vue')['default']
    'LinksWraper copy': typeof import('./src/components/Links/LinksWraper copy.vue')['default']
    Log: typeof import('./src/components/Widgets/Terminal/Log.vue')['default']
    Logs: typeof import('./src/components/Widgets/Terminal/Tabs/Logs.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Node: typeof import('./src/components/Nodes/Node.vue')['default']
    NodeEditor: typeof import('./src/components/NodeEditor.vue')['default']
    NodeHeader: typeof import('./src/components/Nodes/NodeComponents/NodeHeader.vue')['default']
    NodeWraper: typeof import('./src/components/NodeWraper.vue')['default']
    NotificationMessage: typeof import('./src/components/Shared/NotificationMessage.vue')['default']
    NumberInput: typeof import('./src/components/Fields/NumberInput.vue')['default']
    PanningZooming: typeof import('./src/components/PanningZooming.vue')['default']
    PrintNode: typeof import('./src/components/Nodes/PrintNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabWraper: typeof import('./src/components/Shared/TabWraper.vue')['default']
    TemplateNode: typeof import('./src/components/Nodes/TemplateNode.vue')['default']
    TemporaryLink: typeof import('./src/components/Links/TemporaryLink.vue')['default']
    Terminal: typeof import('./src/components/Widgets/Terminal/Terminal.vue')['default']
    TextInput: typeof import('./src/components/Fields/TextInput.vue')['default']
    VariableNode: typeof import('./src/components/Nodes/VariableNode.vue')['default']
    WaveCraftIcon: typeof import('./src/components/Shared/WaveCraftIcon.vue')['default']
    WidgetPannel: typeof import('./src/components/WidgetPannel.vue')['default']
  }
}
